### ISSUE TITLE
Summary shouldn't repeat app name

### ISSUE THREAD

**Issue by razzeee** [flathub/io.github.RobertBeckebans.RBDoom3BFG-GL#1]
You could argue, that the current summary isguilty of https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#dont-repeat-the-name

**Comment by mbugni** [comment]
The `.desktop` comment is ok?

**Comment by razzeee** [comment]
Yeah, I think that's okay. Will probably be hard to write a summary without mentioning Doom at all :)

**Comment by mbugni** [comment]
> Will probably be hard to write a summary without mentioning Doom at all :)

It's just a copy-and-paste from original [README](https://github.com/RobertBeckebans/RBDOOM-3-BFG#readme). I don't want/like to modify original descritptions.

I [adjusted a bit the summary](https://github.com/flathub/io.github.RobertBeckebans.RBDoom3BFG-GL/pull/3) to match the desktop description.

Note:
> This version runs using X11 and OpenGL.

This is not a _technical_ statement, but an important info to distinguish this version from the main-stream one, which uses Vulkan instead.
