### ISSUE TITLE
Suggestion: Classic-RBDOOM-3-BFG  (DOOM-BFA) as Alternative

### ISSUE THREAD

**Issue by Crazy-bat11** [flathub/io.github.RobertBeckebans.RBDoom3BFG-GL#2]
HI, I read the issue you posted on RBDOOM-3-BFG github. As alternative, there is Classic-RBDOOM-3-BFG  (DOOM-BFA):
https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG
It is based on RBDOOM-3-BFG but it is more oriented to gameplay enhancing features. Not only for DOOM 3 BFG, but also DOOM 1 and 2.
I believe you would not have problems packing this port since its latest version (August 09) uses opengl:
https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/releases/tag/1.3.0-BFA.

**Comment by mbugni** [comment]
Hi, this is not an "issue" for this project. It's better to [open a request](https://discourse.flathub.org/c/requests/5) in the [forum category](https://discourse.flathub.org/t/about-the-requests-category/22) to discuss proposals.

Thanks

**Comment by mbugni** [comment]
@Crazy-bat11 you should check the [author intention about Flatpak](https://github.com/MadDeCoDeR/BFA-flatpak-scripts).
